apiVersion: v1
kind: Secret
metadata:
  name: obp-api-secrets
  namespace: biat-banking
type: Opaque
data:
  # Les valeurs sont encodées en base64
  # Exemple: echo -n "password" | base64
  db_url: amRiYzpwb3N0Z3Jlc3FsOi8vZGItc2VydmljZTpwb3N0Z3Jlcy9vYnBfZGI= # jdbc:postgresql://db-service:postgres/obp_db
  db_user: b2JwX3VzZXI= # obp_user
  db_password: b2JwX3Bhc3N3b3Jk # obp_password
  importer_secret: Y2hhbmdlX21l # change_me
  sandbox_data_import_secret: Y2hhbmdlX21l # change_me
  remotedata_secret: Zm9vYmFyYmF6 # foobarbaz