apiVersion: apps/v1
kind: Deployment
metadata:
  name: obp-api-deployment
  labels:
    app: obp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obp-api
  template:
    metadata:
      labels:
        app: obp-api
    spec:
      containers:
      - name: obp-api-container
        image: iheb99/obp-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: OBP_API_DB_HOSTNAME
          value: "postgres-service"
        - name: OBP_API_DB_PORT
          value: "5432"
        - name: OBP_API_DB_USER
          value: "obp_api_user"
        - name: OBP_API_DB_DATABASE
          value: "obp_api_db"
        - name: OBP_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: obp-api-service
spec:
  type: NodePort
  selector:
    app: obp-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30007
