apiVersion: v1
kind: ConfigMap
metadata:
  name: obp-config
data:
  default.props: |
    run.mode=production
    db.driver=org.postgresql.Driver
    db.url=jdbc:postgresql://postgres-service:5432/postgres?sslmode=disable
    db.user=postgres
    db.password=postgres
    connector=mapped
    hostname=http://localhost:8080
    allow_public_views=true
    allow_sandbox_data_import=true
    allow_sandbox_account_creation=true
    allow_account_deletion=true
    payments_enabled=false
    importer_secret=change_me
    sandbox_data_import_secret=change_me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obp-api
  template:
    metadata:
      labels:
        app: obp-api
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo "waiting for postgres..."; sleep 2; done;']
      containers:
      - name: obp-api
        image: iheb99/obp-api:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: obp-config-volume
          mountPath: /props
      volumes:
      - name: obp-config-volume
        configMap:
          name: obp-config
---
apiVersion: v1
kind: Service
metadata:
  name: obp-api-service
spec:
  selector:
    app: obp-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
