apiVersion: apps/v1
kind: Deployment
metadata:
  name: obp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obp-api
  template:
    metadata:
      labels:
        app: obp-api
    spec:
      # SECTION AJOUTÉE : INIT CONTAINER
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zv postgres-service 5432; do echo "Waiting for postgres..."; sleep 2; done;']
      # FIN DE LA SECTION AJOUTÉE
      containers:
      - name: obp-api
        image: iheb99/obp-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: obp-api-service
spec:
  selector:
    app: obp-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
