apiVersion: apps/v1
kind: Deployment
metadata:
  name: obp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obp-api
  template:
    metadata:
      labels:
        app: obp-api
    spec:
      containers:
        - name: obp-api
          image: iheb137/obp-api:latest   # <-- remplace par ton image
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            # Optionnel : en plus du props, on force le mode prod côté JVM
            - name: JAVA_TOOL_OPTIONS
              value: "-Drun.mode=production"
          volumeMounts:
            - name: obp-config
              mountPath: /props
          # Probes (optionnel mais conseillé)
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
      volumes:
        - name: obp-config
          configMap:
            name: obp-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: obp-api-service
spec:
  type: NodePort
  selector:
    app: obp-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 0   # laissez Kubernetes choisir
