apiVersion: v1
kind: ConfigMap
metadata:
  name: obp-api-config
data:
  default.props: |
    # --- Run Mode ---
    run.mode=production

    # --- Database Configuration ---
    db.driver=org.postgresql.Driver
    db.url=jdbc:postgresql://postgres-service:5432/postgres?sslmode=disable
    db.user=postgres
    db.password=postgres

    # --- OBP Application Configuration ---
    connector=mapped
    hostname=http://localhost:8080
    allow_public_views=true
    allow_sandbox_data_import=true
    allow_sandbox_account_creation=true
    allow_account_deletion=true
    payments_enabled=false
    importer_secret=change_me
    sandbox_data_import_secret=change_me
