apiVersion: apps/v1
kind: Deployment
metadata:
  name: obp-api-deployment
  labels:
    app: obp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obp-api
  template:
    metadata:
      labels:
        app: obp-api
    spec:
      # Ce conteneur attend que Postgres soit prêt avant de lancer l'application
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo "waiting for postgres..."; sleep 2; done;']
      containers:
      - name: obp-api
        image: iheb99/obp-api:latest
        ports:
        - containerPort: 8080
        # Injecte les informations de connexion à la base de données
        env:
        - name: OBP_DB_USERNAME
          value: "obp_api_user"
        - name: OBP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: OBP_DB_URL
          value: "jdbc:postgresql://postgres-service:5432/obp_api_db"
