apiVersion: v1
kind: Service
metadata:
  name: obp-api
  namespace: biat-banking
  labels:
    app: obp-api
    environment: ${ENVIRONMENT}
spec:
  selector:
    app: obp-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP